# syntax=docker/dockerfile:1

FROM python

WORKDIR /flask-app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY app.py app.py

EXPOSE 8000

CMD ["python3", "-m", "gunicorn", "-b", "0.0.0.0:8000", "app:app"]
